/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Windows 11
 */
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCLientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuFinanceiro = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuTreinos = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuOpções = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seja bem vindo!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 370, 90));

        jButton1.setBackground(new java.awt.Color(231, 231, 231));
        jButton1.setText("Cadastros");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 200, 70));

        jButton3.setBackground(new java.awt.Color(231, 231, 231));
        jButton3.setText("Financeiro");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 200, 70));

        jButton4.setBackground(new java.awt.Color(231, 231, 231));
        jButton4.setText("Treinos");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 200, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/halteres-no-chao-de-uma-academia-ai-generative.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 640));

        jMenuCadastro.setText("Cadastro");

        jMenuItemCLientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-add-user-24.png"))); // NOI18N
        jMenuItemCLientes.setText("Cadastrar Clientes");
        jMenuCadastro.add(jMenuItemCLientes);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-personal-trainer-24.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar Instrutores");
        jMenuCadastro.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-add-properties-24.png"))); // NOI18N
        jMenuItem2.setText("Cadastrar Treinos");
        jMenuCadastro.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons8-gym-24.png"))); // NOI18N
        jMenuItem3.setText("Cadastrar Máquinas e Aparelhos");
        jMenuCadastro.add(jMenuItem3);

        jMenuBar1.add(jMenuCadastro);

        jMenuFinanceiro.setText("Finaneiro");

        jMenuItem5.setText("Faturamento");
        jMenuFinanceiro.add(jMenuItem5);

        jMenuItem6.setText("Pagamentos");
        jMenuFinanceiro.add(jMenuItem6);

        jMenuItem7.setText("Cobrança Automática");
        jMenuFinanceiro.add(jMenuItem7);

        jMenuItem8.setText("Relatórios e Análises");
        jMenuFinanceiro.add(jMenuItem8);

        jMenuItem9.setText("Configurações Financeiras");
        jMenuFinanceiro.add(jMenuItem9);

        jMenuBar1.add(jMenuFinanceiro);

        jMenuTreinos.setText("Treinos");

        jMenuItem11.setText("Plano de Treinamento");
        jMenuTreinos.add(jMenuItem11);

        jMenuItem12.setText("Exercícios");
        jMenuTreinos.add(jMenuItem12);

        jMenuItem17.setText("Metas e Objetivos");
        jMenuTreinos.add(jMenuItem17);

        jMenuBar1.add(jMenuTreinos);

        jMenuOpções.setText("Opções");
        jMenuBar1.add(jMenuOpções);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFinanceiro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemCLientes;
    private javax.swing.JMenu jMenuOpções;
    private javax.swing.JMenu jMenuTreinos;
    // End of variables declaration//GEN-END:variables
}
